// <auto-generated />
namespace AngularJSDataService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Angularjs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Angularjs));
        
        string IMigrationMetadata.Id
        {
            get { return "201802150536413_Angularjs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
